# Generated by Django 4.0.4 on 2022-09-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_blog_title_blog_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likesCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
