# Generated by Django 4.0.4 on 2022-09-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_blog_id_blog_blogid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likedBy',
            field=models.TextField(default='[]'),
        ),
    ]
